version: '3'
services:
    db:
        image: mcr.microsoft.com/mssql/server
        volumes: 
          - ./db_Datawarehouse/json-data-files:/json-data-files
        environment:
            SA_PASSWORD: ${SQL_SERVER_PASSWORD}
            ACCEPT_EULA: Y
        ports:
            - '14333:1433'

    inittools:
        image: aletasystems/tsqlrunner
        volumes: 
          - ./PreFlywaySQLScripts:/tsqlscripts
        environment:
            SQLCMDSERVER: db
            SQLCMDUSER: sa
            SQLCMDPASSWORD: ${SQL_SERVER_PASSWORD}
        command: '/tooling/execute-sql-scripts.sh'

    flyway:
        image: 'boxfuse/flyway:5.2.4'
        command: '-user=sa -password=${SQL_SERVER_PASSWORD} -url="jdbc:sqlserver://db;databaseName=DataWarehouse" -connectRetries=60 migrate'
        volumes:
            - './db_Datawarehouse/sql:/flyway/sql'
            - './db_Datawarehouse/conf:/flyway/conf'
        depends_on:
            - inittools
            - db